### ISSUE TITLE
When the format of the wav file is float32, calib is not multiplied.

### ISSUE THREAD

**Issue by Hiroshiba** [Eomys/MoSQITo#11]
When the format of the wav file is int16 or int32, calib will be multiplied, but not otherwise.
https://github.com/Eomys/MoSQITo/blob/92a5d5382192fdf449316adf4719bc71f391a9f3/mosqito/functions/shared/load.py#L48-L52

`scipy.io.wavfile.read` can handle these formats as well as float32.
https://docs.scipy.org/doc/scipy/reference/generated/scipy.io.wavfile.read.html

I thought it would be better if calib was multiplied even in the case of float32.

Or you may want to use the soundfile library.
https://pysoundfile.readthedocs.io/en/latest/#soundfile.read

Thanks.

**Comment by mglesser** [comment]
Hello @Hiroshiba thanks for raising this issue. I will include a patch in the next release. I'll keep you updated.

**Comment by Hiroshiba** [comment]
Thanks for the reply! I'm looking forward to it!

**Comment by mglesser** [comment]
Hello @Hiroshiba, I've just published a new release of the package that correct the bug you pointed out. Thanks again.
