### ISSUE TITLE
Calib factor in load function

### ISSUE THREAD

**Issue by ErnestoAvedillo** [Eomys/MoSQITo#14]
Hello 
I am quite new with this library and audio analysis in general, and I need your help on next question.
How you do define the calibration factor in this for the function load?

![image](https://user-images.githubusercontent.com/77380193/127652310-8dc2ddac-22e6-4ddb-b318-7d8599d26f86.png)

This is obviously affecting the results and I don’t find the way to calculate this value.
Thanks for your help.

**Comment by mglesser** [comment]
Hello,
The calibration factor is used, for instance, when you import .wav signals. The data stored in a .wav signal are limited to values  in the range [-1 : 1]. If you record a calibrated signal with a maximal amplitude of let say 3 Pascal, you're recording device will divide the signal by 3 to make it "fit" in the .wav format. When importing the signal in Mosqito, you will have to use calib = 3 to get a signal in Pascal rather then a signal between -1 and 1. If you are importing an acoustic signal in Pascal in .mat or .uff format, you can leave calib=1.

**Comment by ErnestoAvedillo** [comment]
Thank you very much for clarifying
