### ISSUE TITLE
Roughness ERROR: RuntimeWarning divide by zero encountered

### ISSUE THREAD

**Issue by ikhwanuddin** [Eomys/MoSQITo#16]
I was running a code like this:

```
signal, fs = load(True, path) 

roughness = comp_roughness(signal, fs, overlap=0)
```

then the output is:

```
/usr/local/lib/python3.9/site-packages/mosqito/functions/shared/load.py:46: 
WavFileWarning: Chunk (non-data) not understood, skipping it.
  fs, signal = wavfile.read(file)
Roughness is being calculated
/usr/local/lib/python3.9/site-packages/mosqito/functions/shared/conversion.py:43: 
RuntimeWarning: divide by zero encountered in log10
  db = 20 * np.log10(amp / ref)
```

I have checked the output of `comp_roughness()` code:
```
output = {
            "name": "Roughness",
            "values": R,
            "time": time,
        }
```

I believe, it should have an output like that. However, until the end of calculation there is no output as intended above.

this is the link of my audio file:
[https://drive.google.com/file/d/1QRldf0RI5FJGeodXTeSHyQxFsm2_Cxsf/view?usp=sharing](https://drive.google.com/file/d/1QRldf0RI5FJGeodXTeSHyQxFsm2_Cxsf/view?usp=sharing)

I hope you can enlighten me to fix this. Thank you!

**Comment by mglesser** [comment]
Hello @ikhwanuddin,
Hopefully I should be able to spend some time checking your issue tomorow. I'll keep you posted.
Best regards

**Comment by ikhwanuddin** [comment]
I guess I have an update regarding the issue. I found that in the end of my recording there is silent part which has 0 energy. The solution in the mean time is to clean up the silent part to avoid "divide by zero" error.

**Comment by mglesser** [comment]
Hello @ikhwanuddin,
I have just runned the following script, without removing the silence at the end of the file. 
```Python
# Import Audio class
from mosqito.functions.shared.load import load
from mosqito.functions.roughness_danielweber.comp_roughness import comp_roughness

path = <path to your .wav file>

# Load signal
signal, fs = load(
    False,
    path,
)

roughness = comp_roughness(signal, fs, overlap=0)
```
It took a long time to compute (around 5 minutes maybe) as the file is quite heavy (32044672 samples), but at the end I get the expected dictionnary in the "roughness" variable. I can plot the roughness as a function of time with the command:
```plt.plot(roughness['time'], roughness['values'])```

Have you checked that you are using the last version of MOSQITO ? By the way, the "divide by zero encountered in log10" message is only a warning, it shouldn't break the execution of the code.

**Comment by ikhwanuddin** [comment]
Ah thank you! I have already used the latest version. 

I think Roughness has two kind of output:

1. Roughness vs time as a plot
2. a single value of Roughness over time

Actually, about plotting the Roughness you mentioned, it succeeds. However, I did not find the single value of R in the end of calculation, so I guess I can average it manually.

Thank you.
