### ISSUE TITLE
Array as input

### ISSUE THREAD

**Issue by andreasharbo** [Eomys/MoSQITo#2]
Hello!

Very nice project you are doing here.

I have been implementing your algorithms in my software the last couple of days and it seems to work great, the results using the test signals from the ISO standard, line up with the expected results. Which is amazing!!

That said, the functions in the package are very focused around `.wav` file input. Great for many hands-on usages.
In my case I'm dealing with data in arrays, already calibrated, so I had to spend some time picking out the functions I need to use and make my own array size handling. 

My suggestion is to open up the package a bit and exposing the internals to more than just ´.wav´ files or octave levels would increase flexibility a lot!

Right now I don't have the time to make a pull request but I might have in the future. I just thought I would let you know that the algorithms are working for me and I will enjoy any future work you put into this :)

Cheers!

**Comment by mglesser** [comment]
Hello,
It's nice to read that the MoSQITo is flying and has successfully reached other projects. Your suggestion is relevant. If, at some point, we find some time to do some modifications, we'll reach you before to check if we can share some pieces of code.

**Comment by mglesser** [comment]
Hello Andreas,
We have recently updated the architecture of the project (more info in the doc https://github.com/Eomys/MoSQITo/blob/master/documentation/architecture.md). It is now possible to compute the metrics from an array.
