### ISSUE TITLE
issue in calc_nl_loudness

### ISSUE THREAD

**Issue by ErnestoAvedillo** [Eomys/MoSQITo#21]
Hello, 
While reviewing your code, I found something that seems to be incorrect in the calc_nl_loudness function.
In this function, the input parameter is core_loudness and the output parameter as per your comments should be nl_loudness, but you return core_loudness again.
I understand that this is an error.
Thanks for your feedback.

**Comment by mglesser** [comment]
Hello,
The corrections have been included in the new release 0.3.4. Thanks again
If it is ok for you, you can close the issue
