### ISSUE TITLE
Issue in Function calc_nl_lp in file loudness_zwicker_nonlinear_decay.py

### ISSUE THREAD

**Issue by ErnestoAvedillo** [Eomys/MoSQITo#22]
Hello
Into the function calc_nl_lp i find this sentence:
        if abs(ui - nl_lp["uo_last"] < 1e-5 **)** :  # case 2 (charge)
 In my opinion should be 
        if abs(ui - nl_lp["uo_last"] **)** < 1e-5:  # case 2 (charge)
 
Thanks for your help.

**Comment by mglesser** [comment]
You're right, I will correct that and make new release. I'll keep you posted.

**Comment by mglesser** [comment]
Hello,
The corrections have been included in the new release 0.3.4. Thanks again
If it is ok for you, you can close the issue
