### ISSUE TITLE
Proposal to speed up the function calc_main_loudness

### ISSUE THREAD

**Issue by ErnestoAvedillo** [Eomys/MoSQITo#24]
Hello, 
I have a proposal to speed up the function calc_main_loudness. (If this is not the way to make those proposals, please let me know is the first time I use Github in this way)
Instead of working with single values, working with numpy arrays.
It works with all audio files I have been working with but I would like from your side to know if it works for your too.
I have also changed the way I call the function. 
It is not necessary to call it raw by raw. just in one sentence is ok.
With your current procedure you call it:
 ```
  num_sample_level = spec_third.shape[1]
  core_loudness = np.zeros((21, num_sample_level))
  for i in np.arange(num_sample_level - 1):
     core_loudness[:, i] = calc_main_loudness(spec_third[:, i], "diffuse")
```
  With mine is enough (Just be aware that I changed the name adding ea to the one I changed.)
`  core_loudness_ea= calc_main_loudness_ea(spec_third, "diffuse")
`
Here is the code
I hope it helps.
 ```
 def calc_main_loudness_ea(spec_third, field_type):
      """Calculate core loudness
  
      The code is based on BASIC program published in "Program for
      calculating loudness according to DIN 45631 (ISO 532B)", E.Zwicker
      and H.Fastl, J.A.S.J (E) 12, 1 (1991).
      It also corresponds to the following functions of the C program
      published with ISO 532-1:2017:
      - corr_third_octave_intensities
      - f_calc_lcbs
      - f_calc_core_loudness
      - f_corr_loudness
  
      Parameters
      ----------
      spec_third : numpy.ndarray
          A third octave band spectrum [dB ref. 2e-5 Pa]
      field_type : str
          Type of soundfield correspondin to spec_third ("free" or
          "diffuse")
  
      Outputs
      -------
      nm :  numpy.ndarray
          Core loudness
      """
      #
      # Date tables definition (variable names and description according to
      # Zwicker:1991)
      # Ranges of 1/3 octave band levels for correction at low frequencies
      # according to equal loudness contours
      rap = np.array([45, 55, 65, 71, 80, 90, 100, 120])
      # Reduction of 1/3 octave band levels at low frequencies according to
      # equal loudness contours within the eight ranges defined by RAP
      dll = np.array(
          [
              (-32, -24, -16, -10, -5, 0, -7, -3, 0, -2, 0),
              (-29, -22, -15, -10, -4, 0, -7, -2, 0, -2, 0),
              (-27, -19, -14, -9, -4, 0, -6, -2, 0, -2, 0),
              (-25, -17, -12, -9, -3, 0, -5, -2, 0, -2, 0),
              (-23, -16, -11, -7, -3, 0, -4, -1, 0, -1, 0),
              (-20, -14, -10, -6, -3, 0, -4, -1, 0, -1, 0),
              (-18, -12, -9, -6, -2, 0, -3, -1, 0, -1, 0),
              (-15, -10, -8, -4, -2, 0, -3, -1, 0, -1, 0),
          ]
      )
      # Critical band level at absolute threshold without taking into
      # account the transmission characteristics of the ear
      ltq = np.array([30, 18, 12, 8, 7, 6, 5, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])
      # Correction of levels according to the transmission characteristics
      # of the ear
      a0 = np.array(
          [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -0.5, -1.6, -3.2, -5.4, -5.6, -4, -1.5, 2, 5, 12]
      )
      # Level difference between free and diffuse sound fields
      ddf = np.array([0,0,0.5,0.9,1.2,1.6,2.3,2.8,3,2,0,-1.4,-2,-1.9,-1,0.5,3,4,4.3,4,])
      # Adaptation of 1/3 oct. band levels to the corresponding critical
      # band level
      dcb = np.array([-0.25,-0.6,-0.8,-0.8,-0.5,0,0.5,1.1,1.5,1.7,1.8,1.8,1.7,1.6,1.4,1.2,0.8,0.5,0,-0.5,])
      #
      # Correction of 1/3 oct. band levels according to equal loudness
      # contours 'xp' and calculation of the intensities for 1/3 oct.
      # bands up to 315 Hz
  
      #Prepare al arrays to work with
      spec_third_aux = spec_third[:dll.shape[1],:]
      spec_third_aux[:,-1] = 0
      
      # Convert rap, dll in 3 dimensional array
      # 1. generate the array shape
      base_mat = np.ones(dll.shape[0]*dll.shape[1]*spec_third_aux.shape[1]).reshape(dll.shape[0],dll.shape[1],spec_third_aux.shape[1]) 
      # 2. start saving data in rap and DLL in a 3D array
      rap_mat = np.array([base_mat[:,i,:].T * rap for i in np.arange(dll.shape[1])]).transpose(2,0,1)
      dll_mat = np.array([np.multiply(base_mat[:,:,i] , dll) for i in np.arange(spec_third.shape[1])]).transpose(1,2,0)
      spec_third_aux_mat = np.array([np.multiply(base_mat[i,:,:] , spec_third_aux) for i in np.arange(dll.shape[0])])
      #create the the array rap-dll
      rap_dll_mat = rap_mat - dll_mat
      
      #This part substitutes the while loop.
      # create the mask to operate
      logic_mat = spec_third_aux_mat > rap_dll_mat
      dll_result = dll_mat [0,:,:]
      dll_result[logic_mat[0,:,:]] = 0
      for i in np.arange(1,dll_mat.shape[0]-1):
          mask = np.logical_xor(logic_mat[i-1,:,:],logic_mat[i,:,:])
          dll_result[mask] = dll_mat [i,mask]
  
      xp = dll_result +spec_third_aux  
      ti = np.power(10, (xp / 10))
  
      # Determination of levels LCB(1), LCB(2) and LCB(3) within the
      # first three critical bands
      
      gi = np.zeros([3,dll_result.shape[1]])
      gi[0,:] = ti[0:6 , : ].sum(axis = 0)
      gi[1,:] = ti[6:9 , : ].sum(axis = 0)
      gi[2,:] = ti[9:11 , : ].sum(axis = 0)
  
      logic_gi= gi > 0
      lcb = np.zeros([3,dll_result.shape[1]])
      lcb = 10 * np.log10(gi[logic_gi])
      lcb = lcb.reshape (3,dll_result.shape[1])
  
      # Calculation of main loudness
      s = 0.25
      nm = np.zeros([20, spec_third_aux.shape[1]])
      le = np.copy(spec_third[8:,:])
      #le = le.reshape((20))
      le[0:3,:] = lcb
      a0_mat = np.ones(a0.shape[0]*spec_third.shape[1]).reshape(a0.shape[0],spec_third.shape[1])
      a0_mat = (a0_mat.T * a0).T
      le = le - a0_mat
      
      if field_type == "diffuse":
          ddf_mat = np.ones(ddf.shape[0]*spec_third.shape[1]).reshape(ddf.shape[0],spec_third.shape[1])
          ddf_mat = (ddf_mat.T * ddf).T
          le += ddf_mat
      
      ltq_mat = np.ones(ltq.shape[0]*spec_third.shape[1]).reshape(ltq.shape[0],spec_third.shape[1])
      ltq_mat = (ltq_mat.T * ltq).T
      i = le > ltq_mat
      dcb_mat = np.ones(dcb.shape[0]*spec_third.shape[1]).reshape(dcb.shape[0],spec_third.shape[1])
      dcb_mat = (dcb_mat.T * dcb).T
      le[i] -= dcb_mat[i]
  
      mp1 = (0.0635 * np.power(10, 0.025 * ltq_mat))
      mp1 [i == False] = 0
      mp2 = (np.power(1 - s + s * np.power(10, 0.1 * (le- ltq_mat)), 0.25) - 1)
      mp2 [i == False] = 0
  
      nm = np.multiply( mp1 , mp2)
      
      nm [i == False] = 0
      nm[nm < 0] = 0
      current_shape = nm.shape
      nm = np.append(nm,np.zeros(current_shape[1])).reshape(current_shape[0]+1,current_shape[1])
      #
      # Correction of specific loudness in the lowest critical band
      # taking into account the dependance of absolute threshold
      # within this critical band
      korry = 0.4 + 0.32 * nm[0] ** 0.2
      nm[0,korry <= 1] *= korry
      nm[:,-1] = 0
      return nm


```

**Comment by mglesser** [comment]
Thanks a lot for this proposal. I've included it in the next release. I have tagged you as the co-author of the commits so that you appear in the project contributors.

If it is ok for you, you can close the issue.

**Comment by mglesser** [comment]
If you have further code modification proposals, the easyest way to manage your contribution would be:
1. You create a fork of the main mosqito repository. This will create a copy of mosqito in your own github (you can follow this tutorial that is related to another open source software bu that can be transparently adapted to mosqito https://pyleecan.org/fork.pyleecan.html)
2. You modify the code from your repository
3. Once it is done, you create a Pull Request (https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)

Don't hesitate to contact me if it is not clear.

**Comment by ErnestoAvedillo** [comment]
Hello
Thanks for your help
I will try and let you know.
I have some other proposals for loudness_zwicker_lowpass_intp, loudness_zwicker_nonlinear_decay, loudness_zwicker_temporal_weighting that are working for me and also saving time.

I will let you know. Thanks again.

**Comment by mglesser** [comment]
Hi Ernesto,
I've made a comparison of the duration of the loudness computation before and after the merge of your work (see below). I think that the results clearly show the benefit of your work. Thanks again. 

If you agree, I think that we can close this issue. 

**After merge**
Duration for Test signal 6: 26.48 s
Duration for Test signal 7: 26.66 s
Duration for Test signal 8: 26.28 s
Duration for Test signal 9: 27.04 s
Duration for Test signal 10: 2.63 s
Duration for Test signal 11: 2.68 s
Duration for Test signal 12: 2.55 s
Duration for Test signal 13: 2.63 s
Duration for Test signal 14: 33.63 s
Duration for Test signal 15: 29.73 s
Duration for Test signal 16: 10.45 s
Duration for Test signal 17: 8.20 s
Duration for Test signal 18: 5.58 s
Duration for Test signal 19: 6.68 s
Duration for Test signal 20: 6.70 s
Duration for Test signal 21: 6.66 s
Duration for Test signal 22: 4.66 s
Duration for Test signal 23: 6.48 s
Duration for Test signal 24: 6.11 s
Duration for Test signal 25: 6.43 s

**Before merge**
Duration for Test signal 6: 42.23 s
Duration for Test signal 7: 43.20 s
Duration for Test signal 8: 42.60 s
Duration for Test signal 9: 48.43 s
Duration for Test signal 10: 4.08 s
Duration for Test signal 11: 4.06 s
Duration for Test signal 12: 4.12 s
Duration for Test signal 13: 4.11 s
Duration for Test signal 14: 60.60 s
Duration for Test signal 15: 53.31 s
Duration for Test signal 16: 18.59 s
Duration for Test signal 17: 12.61 s
Duration for Test signal 18: 9.58 s
Duration for Test signal 19: 11.39 s
Duration for Test signal 20: 11.56 s
Duration for Test signal 21: 11.55 s
Duration for Test signal 22: 7.75 s
Duration for Test signal 23: 11.28 s
Duration for Test signal 24: 10.56 s
Duration for Test signal 25: 11.11 s

**Comment by ErnestoAvedillo** [comment]
Hello MartinThanks for the information, I am happy to hear that you confirmed the improvement.Of course, you can close the issue.Just let me know if there is any other thing I can help with.Best regardsErnesto


    En lunes, 28 de febrero de 2022, 22:04:45 CET, Martin Glesser ***@***.***> escribió:  
 
 


Hi Ernesto,
I've made a comparison of the duration of the loudness computation before and after the merge of your work (see below). I think that the results clearly show the benefit of your work. Thanks again.

If you agree, I think that we can close this issue.

After merge
Duration for Test signal 6: 26.48 s
Duration for Test signal 7: 26.66 s
Duration for Test signal 8: 26.28 s
Duration for Test signal 9: 27.04 s
Duration for Test signal 10: 2.63 s
Duration for Test signal 11: 2.68 s
Duration for Test signal 12: 2.55 s
Duration for Test signal 13: 2.63 s
Duration for Test signal 14: 33.63 s
Duration for Test signal 15: 29.73 s
Duration for Test signal 16: 10.45 s
Duration for Test signal 17: 8.20 s
Duration for Test signal 18: 5.58 s
Duration for Test signal 19: 6.68 s
Duration for Test signal 20: 6.70 s
Duration for Test signal 21: 6.66 s
Duration for Test signal 22: 4.66 s
Duration for Test signal 23: 6.48 s
Duration for Test signal 24: 6.11 s
Duration for Test signal 25: 6.43 s

Before merge
Duration for Test signal 6: 42.23 s
Duration for Test signal 7: 43.20 s
Duration for Test signal 8: 42.60 s
Duration for Test signal 9: 48.43 s
Duration for Test signal 10: 4.08 s
Duration for Test signal 11: 4.06 s
Duration for Test signal 12: 4.12 s
Duration for Test signal 13: 4.11 s
Duration for Test signal 14: 60.60 s
Duration for Test signal 15: 53.31 s
Duration for Test signal 16: 18.59 s
Duration for Test signal 17: 12.61 s
Duration for Test signal 18: 9.58 s
Duration for Test signal 19: 11.39 s
Duration for Test signal 20: 11.56 s
Duration for Test signal 21: 11.55 s
Duration for Test signal 22: 7.75 s
Duration for Test signal 23: 11.28 s
Duration for Test signal 24: 10.56 s
Duration for Test signal 25: 11.11 s

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
