### ISSUE TITLE
Any way to compute Loudness, Sharpness from a numpy array?

### ISSUE THREAD

**Issue by AlejandroBaron** [Eomys/MoSQITo#29]
I've been checking both source code and examples and my guess is that they can be only computed by providing a path to a .wav file.

Is this correct? Or is there any shortcut to just provide a numpy array containing signal samples and a sample rate, then compute parameters for that signal. I don't wanna fork the project just to be able to do this

**Comment by mglesser** [comment]
Hello, the [comp_sharpness ](https://github.com/Eomys/MoSQITo/blob/master/mosqito/functions/sharpness/comp_sharpness.py ) function can compute sharpness from a numpy array. More information can be found in [the tutorial](https://github.com/Eomys/MoSQITo/blob/master/tutorials/tuto_sharpness.ipynb).
