### ISSUE TITLE
Thanks for your contribution!

### ISSUE THREAD

**Issue by SoulProficiency** [Eomys/MoSQITo#31]
Thanks for your contribution!it helps us a lot！
BTW:I‘m a freshmen in NVH filed and Could you share us some paper or knowledge book about sound quility?
Thanks a lot!

**Comment by mglesser** [comment]
It's nice to hear that MOSQITO is useful! A good entry point to sound quality is the book from Zwicker and Fastl "Psychoacoustics - Facts and Models". If you are more interested in the implementation of the sound quality metrics, you can find good material in the website of the company Head Acoustic.

**Comment by SoulProficiency** [comment]
Thank you very much!

**Comment by SoulProficiency** [comment]
dear author!
In load function,what is the calib parameter used for?I found its default value is 1.and the description is "calibration factor for the signal to be in [pa]" .is that mean the standard atmospheric pressure?

**Comment by mglesser** [comment]
Hello, I've just updated the code to propose a better description of the "calib" input parameter
- in the [load function](https://github.com/Eomys/MoSQITo/blob/master/mosqito/functions/shared/load.py) description
- in the [signal basic operations tutorial](https://github.com/Eomys/MoSQITo/blob/master/tutorials/tuto_signal_basic_operations.ipynb)
