### ISSUE TITLE
Calibration factor

### ISSUE THREAD

**Issue by ashutroll** [Eomys/MoSQITo#34]
Dear author!

I got the same question about the Calib Factor. And I've read other users Issues and your reply,
well I still **don't know how to calculate calib factor precisely,** **is there any **formula?** or using any tools to calculate this value?**

I saw the list below which from other website, and still, no one can explain how to get this value accurate.
1.0 = 91 dBSPL = 1kHz 0 dBFS
2.0 = 96.97 dBSPL = 1kHz 0 dBFS
3.0 = 100.5 dBSPL = 1kHz 0 dBFS
4.0 = 102.9 dBSPL = 1kHz 0 dBFS
5.0 = 104.97 dBSPL = 1kHz 0 dBFS
6.0 = 106.5 dBSPL = 1kHz 0 dBFS
7.0 = 107.83 dBSPL = 1kHz 0 dBFS
8.0 = 109 dBSPL = 1kHz 0 dBFS
9.0 = 110 dBSPL = 1kHz 0 dBFS
10.0 = 111 dBSPL = 1kHz 0 dBFS
11.0 = 111.8 dBSPL = 1kHz 0 dBFS
12.0 = 112.57 dBSPL = 1kHz 0 dBFS

I would be very grateful if you can help me to figure out this value.
Thanks!

**Comment by mglesser** [comment]
Hello, I've answered to the previous issue (sorry for the delay). I should definitely make it clearer as I got this question multiple time. I will update the documentation in the next release.

**Comment by mglesser** [comment]
Hello, I've just updated the code to propose a better description of the "calib" input parameter
- in the [load function](https://github.com/Eomys/MoSQITo/blob/master/mosqito/functions/shared/load.py) description
- in the [signal basic operations tutorial](https://github.com/Eomys/MoSQITo/blob/master/tutorials/tuto_signal_basic_operations.ipynb)

**Comment by ashutroll** [comment]
Thank you, author,
I am appreciate you really did a great job!

So basically, 1 pascal approximately equal to 94 dBSPL.
If the "calib=1" which means I should make sure the .wav file 94dBSPL = 0dBFS.
Am I correct?

**Comment by mglesser** [comment]
I would say that:
1.41 pascal peak => 1 pascal rms => 94 dBSPL => 3 dBFS
1 pascal peak => 0.71 pascal rms => 91 dBSPL => 0 dBFS
If the full scale = 1 Pa.

**Comment by ashutroll** [comment]
Thank you, author,

Now I have more question.
I want to generate 1kHz-94dBSPL signal from microphone calibrator (B&K 4231), and record it to my computer through the Audio Interface (Focusrite Scarlett). 
Well I can adjust Focusrite gain value that makes the recording signal amplitude just right reach to Full Scale[-1:1] like this figure (https://drive.google.com/file/d/1nQ-kjvnwjYEOvE_QFv2XBk54LQ2y31kV/view?usp=sharing).

Now I have a 1kHz-94dBSPL => 0dBFS signal, right? if I want to know the Loudness of this signal, I set "calib=1" in MOSQITO, is that correct??

Would you please tell more about it?
Thanks again!

**Comment by mglesser** [comment]
You're microphone calibrator is delivering (at the microphone membrane position) an acoustic pressure of 1 Pa rms ( => 1 * sqrt(2) Pa peak => 94 dBSPL). To store this in a wav file reaching the Full Scale[-1:1], you have to divide the signal by sqrt(2) so that its max amplitude is 1 peak (this "division" is actually done by the gain you are using for your recording). If you want the loudness of this signal in MOSQITO you then have to use "calib=sqrt(2)".
