### ISSUE TITLE
SciDataTool dependency suppress

### ISSUE THREAD

**Issue by wantysal** [Eomys/MoSQITo#41]
Dear all,

Mosqito can be used either with or without SciDataTool, which is currently only useful to handle output data more easily.
Thus I guess it would be great to suppress SDT from the requirements so as to lighten the installation when using PIP   :)

Same for pytest which is only needed to perform computation tests, but doesn't play a role in the functions called by users. It is just necessary for the developers so as to test their code.

**Comment by mglesser** [comment]
Good idea, you can check the PR #20 that made the pyuff dependancy optional.
