### ISSUE TITLE
Misleading tutorials

### ISSUE THREAD

**Issue by egaudrain** [Eomys/MoSQITo#46]
I've been using MOSQITO in the past as part of my research, and it's a great toolbox!

Now I'm trying to use it again, but the online tutorials refer to a structure that seem totally different from the released version, which is a bit misleading... I initially thought that my installation was broken when the import lines from the tutorial failed, and spent a few hours digging into the depths of pip, wheels, setuptools and the likes... just to find out that you have made a radical architecture change and that the online documentation therefore does not match the release anymore...

Just a suggestion, but perhaps you could host a version of the documentation for the latest release on github.io? Or at least add a link to the relevant folders in the release description:
- https://github.com/Eomys/MoSQITo/tree/v0.3.7/tutorials
- https://github.com/Eomys/MoSQITo/tree/v0.3.7/documentation

Thanks!

**Comment by mglesser** [comment]
Hello Etienne,
We have actually recently made a big architecture update of the toolbox (in order, we hope, to make it easyer to use and to contribute to). Unfortunately, I've been late in producing the release to synchronize the pip package with the github repository. 

I've just made a new pip release that synchronize everything. You can get it through a `pip install --upgrade mosqito`. Sorry for the inconvenience.

By the way, it's nice to see that Mosqito is usefull.
Best regards,
Martin

**Comment by ashutroll** [comment]
> Collaborator

I have a similar question after this big architecture update.
I've used `pip install --upgrade` mosqito to 1.0.8, however seems something goes wrong at the section of "Import mosqito functions".
`from mosqito.utils import load`, `from mosqito.sq_metrics import loudness_zwst` always appear the error like:
**ModuleNotFoundError: No module named 'mosqito.utils'**
**ModuleNotFoundError: No module named 'mosqito.sq_metrics'**
But I tried old version code `from mosqito.functions.shared.load import load` is successfully excute.

I'm not sure if there's any compatibility problem in this situation. My python version is 3.8.8, used IDE Spyder 4.2.5. 
Now I have no idea to fix it, do you have any suggestion? or there is a recommended environment should be used?

Thanks!

**Comment by ashutroll** [comment]
Hi author,

**The problem has been solved, please ignore my previous message.**

I deleted whole old "**MoSQUITo-master**" folder and unzip the newest version, it's workable now.
And i need to upgrade h5py or the AttributeError will appear, not a problem.

Thanks!

**Comment by mglesser** [comment]
Hi @ashutroll,
I'm glad you found the solution by yourself. As you can see with this late answer ,I don't have enough time to take care of the MOSQITO !!
