### ISSUE TITLE
Newer Moore & Glasberg article for time-varying signal.

### ISSUE THREAD

**Issue by Ownezx** [Eomys/MoSQITo#7]
Hi everyone, I'm currently working on loudness as part of my PhD project and wanted to point out that during my research on papers about I found a newer paper on the time-varying loudness that you have in your todo list : [A Loudness Model for Time-Varying Sounds Incorporating Binaural Inhibition](https://dx.doi.org/10.1177%2F2331216516682698).

Additionnally I was wondering if anyone was planning on coding the ISO 532-2 2017 method.

**Comment by mglesser** [comment]
Hi @Ownezx,
Thanks for the paper, we'll consider updating the todo list with this newer reference.

For the moment we don' t have ressources to implement the ISO 532-2 2017 method, but I would be very happy to support anyone who want to get a try.

**Comment by mglesser** [comment]
We can get in touch by email (martin.glesser(a)eomys.com) to discuss this further?

**Comment by mglesser** [comment]
Hi @Ownezx,
I finally released a new version of MOSQITO that reference the paper from Moore & Glasberg that you pointed out. Thanks again for the info.
