### ISSUE TITLE
Assumptions

### ISSUE THREAD

**Issue by Ernestaruan** [Eomys/MoSQITo#79]
Hi,

for parameters like SPL, loudness, and sharpness, they have formulas documented and they align with theory.

My question is whether there are any specific assumptions for the parameter roughness? I don't see any formulas documented for it. Thank you.

**Comment by mglesser** [comment]
Hi @Ernestaruan,
The documentation for the roughness computation can be found [here](https://github.com/Eomys/MoSQITo/blob/master/docs/roughness_dw.md). It is computed accroding to the foloowing paper : 
P.Daniel and R.Weber: Psychoacoustical roughness: implementation of an optimized model, Acustica acta.acustica, 1997.
