### ISSUE TITLE
issue when computing sharpness and loudness

### ISSUE THREAD

**Issue by annezhangxue** [Eomys/MoSQITo#9]
Dear @Eomys 

I have installed the mosqito 0.1.0 package by ‘pip install’ and I can successfully import mosqito, however I got issues when I tried to compute the sharpness and loudness as shown below: 
 
![image](https://user-images.githubusercontent.com/72456658/114322185-11366100-9b1f-11eb-90f5-978ecf6c18fb.png)

Do you happen to know this issue and could you please kindly advise how to handle it?
![image](https://user-images.githubusercontent.com/72456658/114322588-5a87b000-9b21-11eb-9649-a7177b1bdfa3.png)

Thank you very much. 
Best Regards,

**Comment by mglesser** [comment]
Hi @annezhangxue,
I am currently working on a new release of the MOSQITO pip package. It should solve your issue. I will notify you as soon as it will be available (today I hope, maybe tomorrow).

**Comment by annezhangxue** [comment]
Hello @mglesser Thank you very much for the update. 
It is working now.
I looked through the codes, does the library also support block processing with pre-setting window length when calculating time series of sharpness and loudness? 
I have audio file with around 9 hours’ recording of traffic noise. It takes very long computation time when simply applying the function of comp_loudness.
Thanks.

**Comment by mglesser** [comment]
Hello @annezhangxue,
In Mosqito, the Loudness and sharpness of time-varying signals are computed over successive time segments of 2ms (according to the standard). This time resolution is suited for relatively short time signals. In the case of long recordings of traffic noise, I guess that the signal can be divided in time segment of a few seconds or minutes. The signal in each of those segments can be considered as stationnary and computed with the stationnary version of the loudness and sharpness. Another approach if you consider that the signal in each segment is non stationary is to apply the time varying alogrithm and collect statistical parameters to represent the segment (Average, Min/Max, ...).

**Comment by annezhangxue** [comment]
> Hello @annezhangxue,
> In Mosqito, the Loudness and sharpness of time-varying signals are computed over successive time segments of 2ms (according to the standard). This time resolution is suited for relatively short time signals. In the case of long recordings of traffic noise, I guess that the signal can be divided in time segment of a few seconds or minutes. The signal in each of those segments can be considered as stationnary and computed with the stationnary version of the loudness and sharpness. Another approach if you consider that the signal in each segment is non stationary is to apply the time varying alogrithm and collect statistical parameters to represent the segment (Average, Min/Max, ...).

Thanks for the answer @mglesser. Are you also working on the fluctuation strength now? and will you also further work on the package of psychoacoustic annoyance metric? Thank you.

**Comment by mglesser** [comment]
Hello @annezhangxue, two main development are currently ongoing 
- the acoustic roughness
- the tonality "hearing-model' (from ECMA 74)
Fluctuation strengh is on the list of the metrics to be developped, but it is not scheduled for the moment. If you are interested in contributing to the project by imlementing one metric or by sending us some pieces of code that would help us to implement a new metric, you wil be more than welcome. Best regards

**Comment by annezhangxue** [comment]
Hello @mglesser thanks for the update. I am working mainly on deep learning, the applied dataset is from traffic noise, the whole study scope is more or less related to the psychoacoustics, although I don't have acoustic or physics background. Maybe you can have a check on another python package from an EU project: https://github.com/AudioCommons/timbral_models/tree/master/timbral_models
They have also calculated some psychoacoustic metrics. Hope it will inspire somehow.

**Comment by mglesser** [comment]
Hello @annezhangxue, thanks for the link. It's actually inspiring. If you feel that your problem is now solved, I let you close the issue. Otherwise I will be happy to help you further if it is possible.

**Comment by annezhangxue** [comment]
@mglesser yes, thank you, I close the issue now:-)

**Comment by annezhangxue** [comment]
> Hello @annezhangxue,
> In Mosqito, the Loudness and sharpness of time-varying signals are computed over successive time segments of 2ms (according to the standard). This time resolution is suited for relatively short time signals. In the case of long recordings of traffic noise, I guess that the signal can be divided in time segment of a few seconds or minutes. The signal in each of those segments can be considered as stationnary and computed with the stationnary version of the loudness and sharpness. Another approach if you consider that the signal in each segment is non stationary is to apply the time varying alogrithm and collect statistical parameters to represent the segment (Average, Min/Max, ...).

Hello,  @mglesser can I have one more additional question please? Would you consider the traffic noise as stationary or time-varying signal when processing the psychoacoustic metrics? The Zwicker model N5 loudness applies only to time-varying noise, right? Thank you.

**Comment by mglesser** [comment]
Hello,
Actually the difference between the stationary and time-varying Zwicker model is that the second considers temporal weigthing of the total loudness versus time (to simulate the duration dependent behaviour of loudness perception for short impulses). If your signal is varying rapidly, you'd better use time-varying loudness model and extract the N5 loudness for instance. But if your signal is varying slowly, you can use the stationary loudness on succesive time segments of you're signal (length of each segment to be determined depending on your signal) and extract the 5th percentile of the Loudness of all the segments to get a unique value.
This being said, I'm not an expert in traffic noise analysis, you may want to cross check those informations.
Best  regards, Martin

**Comment by annezhangxue** [comment]
> Hello,
> Actually the difference between the stationary and time-varying Zwicker model is that the second considers temporal weigthing of the total loudness versus time (to simulate the duration dependent behaviour of loudness perception for short impulses). If your signal is varying rapidly, you'd better use time-varying loudness model and extract the N5 loudness for instance. But if your signal is varying slowly, you can use the stationary loudness on succesive time segments of you're signal (length of each segment to be determined depending on your signal) and extract the 5th percentile of the Loudness of all the segments to get a unique value.
> This being said, I'm not an expert in traffic noise analysis, you may want to cross check those informations.
> Best regards, Martin

I see, thank you very much:-) @mglesser
